/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.metriport.api.resources.devices.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ProviderSource {
    APPLE("apple"),

    CRONOMETER("cronometer"),

    DEXCOM("dexcom"),

    FITBIT("fitbit"),

    GARMIN("garmin"),

    GOOGLE("google"),

    OURA("oura"),

    TENOVI("tenovi"),

    WHOOP("whoop"),

    WITHINGS("withings");

    private final String value;

    ProviderSource(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
