/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.metriport.api.resources.devices.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Sex {
    MALE("male"),

    FEMALE("female");

    private final String value;

    Sex(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
