/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.metriport.api;

import com.metriport.api.core.ClientOptions;
import com.metriport.api.core.Environment;

public final class MetriportBuilder {
    private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

    private Environment environment = Environment.PRODUCTION;

    public MetriportBuilder apiKey(String apiKey) {
        this.clientOptionsBuilder.addHeader("X-API-Key", apiKey);
        return this;
    }

    public MetriportBuilder environment(Environment environment) {
        this.environment = environment;
        return this;
    }

    public MetriportBuilder url(String url) {
        this.environment = Environment.custom(url);
        return this;
    }

    public Metriport build() {
        clientOptionsBuilder.environment(this.environment);
        return new Metriport(clientOptionsBuilder.build());
    }
}
