/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.metriport.api.resources.medical.facility.types;

import com.metriport.api.resources.commons.types.Address;
import java.util.Optional;

public interface IBaseFacility {
    String getName();

    String getNpi();

    Optional<String> getTin();

    Optional<Boolean> getActive();

    Address getAddress();
}
