/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.metriport.api.resources.medical;

import com.metriport.api.core.ClientOptions;
import com.metriport.api.core.Suppliers;
import com.metriport.api.resources.medical.document.DocumentClient;
import com.metriport.api.resources.medical.facility.FacilityClient;
import com.metriport.api.resources.medical.fhir.FhirClient;
import com.metriport.api.resources.medical.organization.OrganizationClient;
import com.metriport.api.resources.medical.patient.PatientClient;
import java.util.function.Supplier;

public class MedicalClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<DocumentClient> documentClient;

    protected final Supplier<FacilityClient> facilityClient;

    protected final Supplier<FhirClient> fhirClient;

    protected final Supplier<OrganizationClient> organizationClient;

    protected final Supplier<PatientClient> patientClient;

    public MedicalClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.documentClient = Suppliers.memoize(() -> new DocumentClient(clientOptions));
        this.facilityClient = Suppliers.memoize(() -> new FacilityClient(clientOptions));
        this.fhirClient = Suppliers.memoize(() -> new FhirClient(clientOptions));
        this.organizationClient = Suppliers.memoize(() -> new OrganizationClient(clientOptions));
        this.patientClient = Suppliers.memoize(() -> new PatientClient(clientOptions));
    }

    public DocumentClient document() {
        return this.documentClient.get();
    }

    public FacilityClient facility() {
        return this.facilityClient.get();
    }

    public FhirClient fhir() {
        return this.fhirClient.get();
    }

    public OrganizationClient organization() {
        return this.organizationClient.get();
    }

    public PatientClient patient() {
        return this.patientClient.get();
    }
}
