/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.metriport.api.resources.medical.patient.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.metriport.api.core.ObjectMappers;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = PatientList.Builder.class)
public final class PatientList {
    private final String facilityId;

    private PatientList(String facilityId) {
        this.facilityId = facilityId;
    }

    /**
     * @return The ID of the Facility where the patient is receiving care.
     */
    @JsonProperty("facilityId")
    public String getFacilityId() {
        return facilityId;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PatientList && equalTo((PatientList) other);
    }

    private boolean equalTo(PatientList other) {
        return facilityId.equals(other.facilityId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.facilityId);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FacilityIdStage builder() {
        return new Builder();
    }

    public interface FacilityIdStage {
        _FinalStage facilityId(String facilityId);

        Builder from(PatientList other);
    }

    public interface _FinalStage {
        PatientList build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FacilityIdStage, _FinalStage {
        private String facilityId;

        private Builder() {}

        @Override
        public Builder from(PatientList other) {
            facilityId(other.getFacilityId());
            return this;
        }

        /**
         * <p>The ID of the Facility where the patient is receiving care.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("facilityId")
        public _FinalStage facilityId(String facilityId) {
            this.facilityId = facilityId;
            return this;
        }

        @Override
        public PatientList build() {
            return new PatientList(facilityId);
        }
    }
}
